### ISSUE TITLE
Missing video in the readme.

### ISSUE THREAD

**Issue by theRingleman** [learn-co-curriculum/rails-video-review-loading-comments-via-get-ajax#1]
The video that is supposed to be there is missing. Maybe just a link to the youtube page could correct this. Also, this is how it is on all the videos that pertain to the rails javascript final section. Thanks!

**Comment by PeterBell** [comment]
Good catch @theRingleman - hey @mendelB do you have the link for this video - or @AnnJohn ?

**Comment by AnnJohn** [comment]
hi @theRingleman and @PeterBell, i'll update this with a link to the video. thanks!

**Comment by theRingleman** [comment]
Awesome @AnnJohn I will link to a couple other repos that are the same way.

https://github.com/learn-co-curriculum/rails-video-review-rails-and-ajax-submitting-a-form
https://github.com/learn-co-curriculum/rails-video-review-adding-form-fields-via-ajax
https://github.com/learn-co-curriculum/rails-video-review-handlebars-and-js-prototypes

**Comment by AnnJohn** [comment]
thanks @theRingleman will update all of them before the end of the day today.

**Comment by AnnJohn** [comment]
hi @theRingleman we updated the links in the [Rails assessment lesson](https://github.com/learn-co-curriculum/rails-js-assessment)  with the youtube links for the videos so you can ignore these repos and just watch the videos from that lesson. thanks!
