### ISSUE TITLE
Video Resolution

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/rails-video-review-loading-comments-via-get-ajax#2]
Video is 360p making it hard to see the words on the screen.

**Comment by DanL12186** [comment]
You can select up to 720P.

**Comment by itzsaga** [comment]
I can't. Other videos work just fine which leads me to believe it's not on my side.
![screenshot from 2017-06-18 18-42-49](https://user-images.githubusercontent.com/11750061/27265161-1480925e-5456-11e7-9619-9f2721ae2e2c.png)

**Comment by itzsaga** [comment]
So, I think this is because of Opera. Closing.
